<?xml version="1.0" encoding="UTF-8"?><testrun name="PedidoDAOTest (1)" project="webpizzaria" tests="4" started="4" failures="0" errors="1" ignored="0">
  <testsuite name="funcional.PedidoDAOTest" time="2.503">
    <testcase name="testIncluirPedido" classname="funcional.PedidoDAOTest" time="0.745"/>
    <testcase name="testIncluirPedidoClienteInvalido" classname="funcional.PedidoDAOTest" time="0.627"/>
    <testcase name="testIncluirPedidoPizzaInvalida" classname="funcional.PedidoDAOTest" time="0.568"/>
    <testcase name="testIncluirPedidoPagamentoInvalido" classname="funcional.PedidoDAOTest" time="0.563">
      <error>java.lang.Exception: Unexpected exception, expected&lt;excecoes.ExcecaoDAO&gt; but was&lt;excecoes.ExcecaoDePedido&gt;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: excecoes.ExcecaoDePedido: pedido.pagamento.invalido
	at dominio.Pedido.validarPagamento(Pedido.java:134)
	at dominio.Pedido.definirPagamento(Pedido.java:74)
	at controlador.MantenedorDeRegistros.incluirPedido(MantenedorDeRegistros.java:110)
	at funcional.PedidoDAOTest.testIncluirPedidoPagamentoInvalido(PedidoDAOTest.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 17 more

</error>
    </testcase>
  </testsuite>
</testrun>
