<?xml version="1.0" encoding="UTF-8"?><testrun name="PizzariaTestSuite" project="pizzaria" tests="11" started="11" failures="0" errors="1" ignored="0">
  <testsuite name="funcional.PizzariaTestSuite" time="5.704">
    <testsuite name="funcional.CadastrarPizzaTest" time="1.973">
      <testcase name="testCadastrarPizzaPrecoInvalido" classname="funcional.CadastrarPizzaTest" time="1.09"/>
      <testcase name="testCadastrarPizzaNomeInvalido" classname="funcional.CadastrarPizzaTest" time="0.493"/>
      <testcase name="testCadastrarPizza" classname="funcional.CadastrarPizzaTest" time="0.231"/>
      <testcase name="testCadastrarPizzaIngredientesInvalido" classname="funcional.CadastrarPizzaTest" time="0.157"/>
    </testsuite>
    <testsuite name="funcional.CadastrarClienteTest" time="1.346">
      <testcase name="testCadastrarClienteComEnderecoInvalido" classname="funcional.CadastrarClienteTest" time="0.158"/>
      <testcase name="testCadastrarClienteComTelefoneInvalido" classname="funcional.CadastrarClienteTest" time="0.205"/>
      <testcase name="testCadastrarClienteComNomeInvalido" classname="funcional.CadastrarClienteTest" time="0.364"/>
      <testcase name="testCadastrarCliente" classname="funcional.CadastrarClienteTest" time="0.619"/>
    </testsuite>
    <testsuite name="funcional.CadastrarPedidoTest" time="2.385">
      <testcase name="testCadastrarPedidoPizzaNaoExistente" classname="funcional.CadastrarPedidoTest" time="1.141"/>
      <testcase name="testCadastrarPedidoClienteNaoExistente" classname="funcional.CadastrarPedidoTest" time="0.646"/>
      <testcase name="testCadastrarPedido" classname="funcional.CadastrarPedidoTest" time="0.598">
        <error>excecoes.ExcecaoDAO: pedido_dao.nao_foi_possivel_incluir_o_pedido
	at pizzariaDAO.PedidoDAOConcreto.incluir(PedidoDAOConcreto.java:42)
	at controlador.MantenedorDeRegistros.incluirPedido(MantenedorDeRegistros.java:68)
	at funcional.CadastrarPedidoTest.testCadastrarPedido(CadastrarPedidoTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.postgresql.util.PSQLException: ERROR: column "id_cliente_fk" of relation "pedido" does not exist
  Position: 29
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:412)
	at pizzariaDAO.PedidoDAOConcreto.incluir(PedidoDAOConcreto.java:39)
	... 29 more

</error>
      </testcase>
    </testsuite>
  </testsuite>
</testrun>
